server:
  port: 8080
  address: 0.0.0.0

# ==================================
# APP
# ==================================
spring:
  application:
    name: MediKeep

  # ==================================
  # DATABASE (MySQL)
  # ==================================
  datasource:
    url: jdbc:mysql://localhost:3306/medikeep?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: "youngh29ktj!"   # 비밀번호 특수문자 있으면 따옴표 필수
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ==================================
  # JPA & HIBERNATE
  # ==================================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# ==================================
# JWT
# ==================================
jwt:
  secret:
    key: ${JWT_SECRET_KEY:bWVkaWtlZXAtaXMtYW4tYXdlc29tZS1wcm9qZWN0LWZvci1tYW5hZ2luZy1tZWRpY2F0aW9u}